brand:
  name: VitrineAlu
  tagline: "Bring light into living"
  colors:
    primary: "#0C2436"
    accent:  "#1274B7"
    light:   "#F5F7FA"
    white:   "#FFFFFF"
  fonts:
    heading: "Poppins-SemiBold"
    body:    "Inter-Regular"
  watermark:
    file: "/assets/brand/logo-white.png"
    opacity: 0.7
    position: "bottom-right"
    margin_px: 32
text_overlay:
  safe_area_pct: { top: 12, bottom: 18, sides: 8 }
