# Brand Kit Configuration for Media Ingest Service
# Copy this file to config/brand.yaml and customize for your brand

brand: vitrinealu

# Brand colors (hex codes)
colors:
  primary: "#0066CC"
  secondary: "#FF6600"
  accent: "#00CC66"

# Typography settings
fonts:
  primary: "Arial"
  secondary: "Helvetica"
  heading: "Arial Black"

# Watermark configuration
watermark:
  path: "/path/to/your/logo.png"
  opacity: 0.8
  scale: 0.15
  position: "bottom-right"
  margin: 20

# Supported aspect ratios for responsive design
aspect_ratios:
  - "16:9"
  - "4:3"
  - "1:1"
  - "3:2"

# Brand guidelines
guidelines:
  max_logo_width_percent: 15
  min_contrast_ratio: 4.5
  preferred_formats: ["JPG", "PNG", "WebP"]